name: Publish hcss jupyternotebook bert docker image

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push hcss jupyternotebook bert docker images to deployment server
    runs-on: ubuntu-latest

    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push hcss jupyternotebook M docker
        uses: docker/build-push-action@v5
        with:
          push: true
          target: hcss-jupyternotebook-bert
          tags: |
            ghcr.io/hcss-data-lab/nlp-pipeline-bert/hcss_jupyternotebook_bert:latest
